language: go

sudo: false

go:
- 1.7

install:
  - go get -d -t -v ./...
  - go build ./...

script:
- go test -race -covermode=atomic -coverprofile=memory.txt ./service/memory
- cat memory.txt >> coverage.txt
- go test -race -covermode=atomic -coverprofile=redis.txt ./service/redis
- cat redis.txt >> coverage.txt

notifications:
  email: false

branches:
  only:
    - master

after_success:
- bash <(curl -s https://codecov.io/bash)
